workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    environment:
      node: 18.18.0
      xcode: latest
      cocoapods: default
      vars:
        EXPO_TOKEN: $EXPO_TOKEN  # Set this in Codemagic UI
        PACKAGE_NAME: "com.pdlebhaii.app"
    scripts:
      - name: Install dependencies
        script: |
          cd pen
          # Set CI environment variable
          export CI=1
          # Clear npm cache
          npm cache clean --force
          # Install global tools
          npm install -g eas-cli
          # Create .npmrc with auth token if EXPO_TOKEN is set
          if [ -n "$EXPO_TOKEN" ]; then
            echo "//registry.npmjs.org/:_authToken=$EXPO_TOKEN" > .npmrc
          fi
          # Install dependencies with specific React version
          npm install --legacy-peer-deps
          # Install Expo CLI and dependencies using npm with legacy peer deps
          npm install --legacy-peer-deps expo-cli --save-dev
          # Install Expo managed dependencies
          npm install --legacy-peer-deps expo
      - name: Set up EAS
        script: |
          cd pen
          # Create a basic eas.json if it doesn't exist
          if [ ! -f "eas.json" ]; then
            echo '{
              "cli": {
                "version": ">= 5.9.1"
              },
              "build": {
                "development": {
                  "developmentClient": true,
                  "distribution": "internal",
                  "android": {
                    "gradleCommand": ":app:assembleDebug"
                  }
                },
                "preview": {
                  "distribution": "internal"
                },
                "production": {}
              }
            }' > eas.json
          fi
          
          # Skip EAS config for local builds
          echo "EAS configuration complete. Proceeding with local build..."
      - name: Install JavaScript Dependencies
        script: |
          cd pen
          # Clean npm cache and reinstall dependencies
          npm cache clean --force
          rm -rf node_modules
          npm install --legacy-peer-deps
          
      - name: Build Android Debug
        script: |
          cd pen
          # Generate Android project files
          npx expo prebuild --platform android --clean --no-install
          
          # Fix potential permission issues
          chmod +x android/gradlew
          
          # Build the Android app
          cd android
          ./gradlew clean assembleDebug --info
      - name: Build Android Release
        script: |
          cd pen
          npx expo prebuild --platform android --clean
          cd android
          ./gradlew assembleRelease
    artifacts:
      - pen/android/app/build/outputs/**/*.apk
      - pen/android/app/build/outputs/**/*.aab
      - pen/android/app/build/outputs/mapping/**/mapping.txt
    publishing:
      email:
        recipients:
          - tanisha5721k@gmail.com
      scripts:
        - name: Notify
          script: |
            echo "Build completed successfully!"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
